use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use xenor_engine_rust::{
    SettlementArtifactDigests, SettlementArtifactSizes, SettlementDemoCatalog,
    SettlementDemoScenarioView, SettlementDeterminismReport, SettlementRunSummary,
    SettlementScenarioExpectation, SettlementSimulationConfig, SettlementStatus,
    SettlementTickDigestView, WorkerAllocation, build_settlement_demo_catalog,
};

fn main() -> Result<(), Box<dyn Error>> {
    let output_path = env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(default_output_path);
    let catalog = build_settlement_demo_catalog()?;
    let rendered = render_catalog_module(&catalog);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output_path, rendered)?;

    println!("wrote {}", output_path.display());
    Ok(())
}

fn default_output_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../xenor-web/app/lib/generated/settlement-demo.generated.ts")
}

fn render_catalog_module(catalog: &SettlementDemoCatalog) -> String {
    let mut out = String::new();
    out.push_str("import type { SettlementDemoCatalog } from \"../settlement-demo-contract\";\n\n");
    out.push_str("// Generated by `cargo run --manifest-path rust/Cargo.toml --example settlement_site_demo`.\n");
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("export const settlementDemoCatalog = {\n");
    push_line(
        &mut out,
        1,
        format!("engineFamily: {},", js_string(&catalog.engine_family)),
    );
    push_line(
        &mut out,
        1,
        format!("scenarioCount: {},", catalog.scenario_count),
    );
    push_line(&mut out, 1, "scenarios: [".into());
    for scenario in &catalog.scenarios {
        render_scenario(&mut out, scenario, 2);
    }
    push_line(&mut out, 1, "],".into());
    out.push_str("} satisfies SettlementDemoCatalog;\n");
    out
}

fn render_scenario(out: &mut String, scenario: &SettlementDemoScenarioView, indent: usize) {
    push_line(out, indent, "{".into());
    push_line(out, indent + 1, format!("id: {},", js_string(&scenario.id)));
    push_line(
        out,
        indent + 1,
        format!("title: {},", js_string(&scenario.title)),
    );
    push_line(
        out,
        indent + 1,
        format!("description: {},", js_string(&scenario.description)),
    );
    push_line(
        out,
        indent + 1,
        format!("seed: {},", js_string(&scenario.seed.to_string())),
    );
    push_line(
        out,
        indent + 1,
        format!("tickCount: {},", scenario.tick_count),
    );
    push_line(out, indent + 1, "config: {".into());
    render_config(out, &scenario.config, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "expected: {".into());
    render_expectation(out, &scenario.expected, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "runSummary: {".into());
    render_run_summary(out, &scenario.run_summary, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "artifactSummary: {".into());
    render_artifact_summary(out, scenario, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "artifactDigests: {".into());
    render_artifact_digests(out, &scenario.artifact_digests, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "artifactSizes: {".into());
    render_artifact_sizes(out, &scenario.artifact_sizes, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent + 1, "tickDigestView: [".into());
    for tick in &scenario.tick_digest_view {
        render_tick_digest(out, tick, indent + 2);
    }
    push_line(out, indent + 1, "],".into());
    push_line(out, indent + 1, "determinism: {".into());
    render_determinism(out, &scenario.determinism, indent + 2);
    push_line(out, indent + 1, "},".into());
    push_line(out, indent, "},".into());
}

fn render_config(out: &mut String, config: &SettlementSimulationConfig, indent: usize) {
    push_line(out, indent, format!("population: {},", config.population));
    push_line(
        out,
        indent,
        format!("initialFood: {},", config.initial_food),
    );
    push_line(
        out,
        indent,
        format!("initialWood: {},", config.initial_wood),
    );
    push_line(out, indent, "initialAllocation: {".into());
    render_allocation(out, config.initial_allocation, indent + 1);
    push_line(out, indent, "},".into());
    push_line(
        out,
        indent,
        format!("foodPerFarmer: {},", config.food_per_farmer),
    );
    push_line(
        out,
        indent,
        format!("woodPerLogger: {},", config.wood_per_logger),
    );
    push_line(
        out,
        indent,
        format!(
            "foodConsumptionPerWorker: {},",
            config.food_consumption_per_worker
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "woodConsumptionPerTick: {},",
            config.wood_consumption_per_tick
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "snapshotPolicy: {},",
            js_string(&config.snapshot_policy.canonical_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "validationPolicy: {},",
            js_string(config.validation_policy.as_str())
        ),
    );
    push_line(
        out,
        indent,
        format!("maxInventory: {},", config.max_inventory),
    );
}

fn render_expectation(
    out: &mut String,
    expectation: &SettlementScenarioExpectation,
    indent: usize,
) {
    push_line(out, indent, "finalAllocation: {".into());
    render_allocation(out, expectation.final_allocation, indent + 1);
    push_line(out, indent, "},".into());
    push_line(
        out,
        indent,
        format!("finalFood: {},", expectation.final_food),
    );
    push_line(
        out,
        indent,
        format!("finalWood: {},", expectation.final_wood),
    );
    push_line(
        out,
        indent,
        format!(
            "finalStatus: {},",
            js_string(expectation.final_status.as_str())
        ),
    );
    push_line(
        out,
        indent,
        format!("shortageTicks: {},", expectation.shortage_ticks),
    );
    push_line(
        out,
        indent,
        format!("totalFoodProduced: {},", expectation.total_food_produced),
    );
    push_line(
        out,
        indent,
        format!("totalWoodProduced: {},", expectation.total_wood_produced),
    );
    push_line(
        out,
        indent,
        format!("totalFoodShortage: {},", expectation.total_food_shortage),
    );
    push_line(
        out,
        indent,
        format!("totalWoodShortage: {},", expectation.total_wood_shortage),
    );
}

fn render_run_summary(out: &mut String, summary: &SettlementRunSummary, indent: usize) {
    push_line(out, indent, format!("finalTick: {},", summary.final_tick));
    push_line(out, indent, format!("population: {},", summary.population));
    push_line(out, indent, "finalAllocation: {".into());
    render_allocation(out, summary.final_allocation, indent + 1);
    push_line(out, indent, "},".into());
    push_line(
        out,
        indent,
        format!("idleWorkers: {},", summary.idle_workers),
    );
    push_line(out, indent, format!("finalFood: {},", summary.final_food));
    push_line(out, indent, format!("finalWood: {},", summary.final_wood));
    push_line(
        out,
        indent,
        format!("lastStatus: {},", js_string(summary.last_status.as_str())),
    );
    push_line(
        out,
        indent,
        format!("shortageTicks: {},", summary.shortage_ticks),
    );
    push_line(
        out,
        indent,
        format!("totalFoodProduced: {},", summary.total_food_produced),
    );
    push_line(
        out,
        indent,
        format!("totalWoodProduced: {},", summary.total_wood_produced),
    );
    push_line(
        out,
        indent,
        format!("totalFoodConsumed: {},", summary.total_food_consumed),
    );
    push_line(
        out,
        indent,
        format!("totalWoodConsumed: {},", summary.total_wood_consumed),
    );
    push_line(
        out,
        indent,
        format!("totalFoodShortage: {},", summary.total_food_shortage),
    );
    push_line(
        out,
        indent,
        format!("totalWoodShortage: {},", summary.total_wood_shortage),
    );
    push_line(
        out,
        indent,
        format!(
            "finalChecksum: {},",
            js_string(&summary.final_checksum.to_string())
        ),
    );
}

fn render_artifact_summary(out: &mut String, scenario: &SettlementDemoScenarioView, indent: usize) {
    push_line(
        out,
        indent,
        format!("baseSeed: {},", js_string(&scenario.seed.to_string())),
    );
    push_line(
        out,
        indent,
        format!("finalTick: {},", scenario.artifact_summary.final_tick),
    );
    push_line(
        out,
        indent,
        format!(
            "finalChecksum: {},",
            js_string(&scenario.artifact_summary.final_checksum.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "configPayloadSchemaVersion: {},",
            scenario.artifact_summary.config_payload_schema_version
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "configDigest: {},",
            js_string(&scenario.artifact_summary.config_digest.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "replayDigest: {},",
            js_string(&scenario.artifact_summary.replay_digest.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "snapshotDigest: {},",
            render_optional_u64(scenario.artifact_summary.snapshot_digest)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "scenarioDigest: {},",
            render_optional_u64(scenario.artifact_summary.scenario_digest)
        ),
    );
}

fn render_artifact_digests(out: &mut String, digests: &SettlementArtifactDigests, indent: usize) {
    push_line(
        out,
        indent,
        format!(
            "configArtifact: {},",
            js_string(&digests.config_artifact.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "scenarioArtifact: {},",
            render_optional_u64(digests.scenario_artifact)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "replayArtifact: {},",
            js_string(&digests.replay_artifact.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "snapshotArtifact: {},",
            render_optional_u64(digests.snapshot_artifact)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "goldenFixture: {},",
            render_optional_u64(digests.golden_fixture)
        ),
    );
}

fn render_artifact_sizes(out: &mut String, sizes: &SettlementArtifactSizes, indent: usize) {
    push_line(
        out,
        indent,
        format!("configArtifact: {},", sizes.config_artifact),
    );
    push_line(
        out,
        indent,
        format!(
            "scenarioArtifact: {},",
            render_optional_usize(sizes.scenario_artifact)
        ),
    );
    push_line(
        out,
        indent,
        format!("replayArtifact: {},", sizes.replay_artifact),
    );
    push_line(
        out,
        indent,
        format!(
            "snapshotArtifact: {},",
            render_optional_usize(sizes.snapshot_artifact)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "goldenFixture: {},",
            render_optional_usize(sizes.golden_fixture)
        ),
    );
}

fn render_tick_digest(out: &mut String, tick: &SettlementTickDigestView, indent: usize) {
    push_line(out, indent, "{".into());
    push_line(out, indent + 1, format!("tick: {},", tick.tick));
    push_line(
        out,
        indent + 1,
        format!("checksum: {},", js_string(&tick.checksum.to_string())),
    );
    push_line(
        out,
        indent + 1,
        format!(
            "snapshotPresent: {},",
            if tick.snapshot_present {
                "true"
            } else {
                "false"
            }
        ),
    );
    push_line(
        out,
        indent + 1,
        format!("phaseOrder: {},", render_string_array(&tick.phase_order)),
    );
    push_line(
        out,
        indent + 1,
        format!(
            "validationCheckpoints: {},",
            render_string_array(&tick.validation_checkpoints)
        ),
    );
    push_line(out, indent, "},".into());
}

fn render_determinism(out: &mut String, determinism: &SettlementDeterminismReport, indent: usize) {
    push_line(
        out,
        indent,
        format!(
            "expectationPassed: {},",
            if determinism.expectation_check.passed {
                "true"
            } else {
                "false"
            }
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "expectationDetail: {},",
            render_optional_string(determinism.expectation_check.detail.as_deref())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "rerunParityMatch: {},",
            if determinism.rerun_parity_match {
                "true"
            } else {
                "false"
            }
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "replayVerificationMatch: {},",
            if determinism.replay_verification_match {
                "true"
            } else {
                "false"
            }
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "replayVerificationChecksum: {},",
            js_string(&determinism.replay_verification_checksum.to_string())
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "resumeSnapshotTick: {},",
            render_optional_tick(determinism.resume_snapshot_tick)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "resumeFromSnapshotMatch: {},",
            if determinism.resume_from_snapshot_match {
                "true"
            } else {
                "false"
            }
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "resumeFromSnapshotChecksum: {},",
            render_optional_u64(determinism.resume_from_snapshot_checksum)
        ),
    );
    push_line(
        out,
        indent,
        format!(
            "fixtureVerificationPassed: {},",
            if determinism.fixture_verification_passed {
                "true"
            } else {
                "false"
            }
        ),
    );
}

fn render_allocation(out: &mut String, allocation: WorkerAllocation, indent: usize) {
    push_line(out, indent, format!("farmers: {},", allocation.farmers));
    push_line(out, indent, format!("loggers: {},", allocation.loggers));
}

fn render_string_array(values: &[String]) -> String {
    let rendered = values
        .iter()
        .map(|value| js_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered}]")
}

fn render_optional_string(value: Option<&str>) -> String {
    value.map(js_string).unwrap_or_else(|| "null".into())
}

fn render_optional_u64(value: Option<u64>) -> String {
    value
        .map(|value| js_string(&value.to_string()))
        .unwrap_or_else(|| "null".into())
}

fn render_optional_usize(value: Option<usize>) -> String {
    value
        .map(|value| value.to_string())
        .unwrap_or_else(|| "null".into())
}

fn render_optional_tick(value: Option<u64>) -> String {
    value
        .map(|value| value.to_string())
        .unwrap_or_else(|| "null".into())
}

fn js_string(value: &str) -> String {
    format!("{value:?}")
}

fn push_line(out: &mut String, indent: usize, content: String) {
    let _ = writeln!(out, "{}{}", "  ".repeat(indent), content);
}

#[allow(dead_code)]
fn _status_as_str(status: SettlementStatus) -> &'static str {
    status.as_str()
}
